#!/bin/bash

function untitled() {
    suffix=$(cat $1)
    filename="Untitled $suffix"
    i=1
    while [[ -e "$filename.txt" ]]; do
        filename="Untitled $suffix ($i)"
        ((i++))
    done
    touch "$filename.txt"
    echo "$filename.txt created."
}
